name: Fetch GitHub Sponsors

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  fetch-sponsors:
    runs-on: tenki-standard-medium-4c-8g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          

      - name: Fetch GitHub Sponsors
        env:
          SPONSORS_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
        run: python scripts/fetch-sponsors.py

      - name: Configure Git
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            

      - name: Commit and Push Sponsors JSON
        run: |
            git add meta/sponsors.json
            git commit -m "Update Sponsors" || true
            git push || true